// Configuración de Tailwind del sitio: es la única fuente. Antes estaba copiada
// inline en cada página (<script id="tailwind-config">) para el CDN.
// Después de cambiar clases en los HTML o esta config, corré `npm run build:css`.

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#979793",
        "secondary": "#8dd4c0",
        "inverse-on-surface": "#303030",
        "primary-fixed": "#c2ecd6",
        "primary-container": "#0f3627",
        "on-tertiary-fixed": "#1a1c19",
        "on-secondary-fixed": "#002019",
        "tertiary-fixed": "#e3e3de",
        "surface-container": "#1f2020",
        "error-container": "#93000a",
        "on-surface": "#e4e2e1",
        "on-primary-fixed": "#002115",
        "on-primary": "#103728",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#005849",
        "on-secondary-fixed-variant": "#005143",
        "on-primary-fixed-variant": "#294e3d",
        "error": "#ffb4ab",
        "surface-dim": "#131313",
        "secondary-fixed": "#a8f1dc",
        "outline-variant": "#414844",
        "surface-variant": "#353535",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#2e302d",
        "inverse-surface": "#e4e2e1",
        "on-secondary": "#00382d",
        "primary": "#a7d0ba",
        "outline": "#8b938d",
        "on-tertiary": "#2f312e",
        "on-tertiary-fixed-variant": "#464744",
        "surface-container-highest": "#353535",
        "surface-container-lowest": "#0e0e0e",
        "surface": "#131313",
        "on-primary-container": "#78a08c",
        "secondary-fixed-dim": "#8dd4c0",
        "surface-container-low": "#1b1c1c",
        "on-background": "#e4e2e1",
        "inverse-primary": "#406654",
        "surface-bright": "#393939",
        "tertiary-fixed-dim": "#c7c7c2",
        "surface-tint": "#a7d0ba",
        "on-surface-variant": "#c1c8c2",
        "on-error": "#690005",
        "tertiary": "#c7c7c2",
        "primary-fixed-dim": "#a7d0ba",
        "background": "#131313",
        "on-secondary-container": "#85cdb9",
        "teal-accent": "#367E6D",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "max-width": "1080px",
        "base": "4px",
        "unit": "7px",
        "section-v-md": "70px",
        "margin-page": "28px",
        "gutter": "28px",
        "section-v-lg": "84px",
        "grid-gap": "20px",
      },
      fontFamily: {
        "display-h1": ["Rubik"],
        "mono-eyebrow": ["JetBrains Mono"],
        "body-small": ["Rubik"],
        "section-h2": ["Rubik"],
        "ui-action": ["JetBrains Mono"],
        "mono-data": ["JetBrains Mono"],
        "display-h1-mobile": ["Rubik"],
        "card-h3": ["Rubik"],
        "body-main": ["Rubik"],
      },
      fontSize: {
        "display-h1": ["54px", { lineHeight: "1.08", letterSpacing: "-0.02em", fontWeight: "900" }],
        "mono-eyebrow": ["12px", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-small": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "section-h2": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "900" }],
        "ui-action": ["12.5px", { lineHeight: "1", fontWeight: "500" }],
        "mono-data": ["13px", { lineHeight: "1.4", fontWeight: "500" }],
        "display-h1-mobile": ["32px", { lineHeight: "1.1", fontWeight: "900" }],
        "card-h3": ["18px", { lineHeight: "1.4", fontWeight: "700" }],
        "body-main": ["17.5px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
